name: GitHub Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Output event name
      run: 'echo "Event: ${{ github.event_name }}"'
    - name: Output current branch or ref name
      run: 'echo "Branch: ${{ github.ref_name }}"'
    - name: List all files in the repository
      run: ls -R
